import React, { useState } from "react";
import { PageHeader } from "@/components/common/PageHeader";
import { DataTable, Column } from "@/components/common/DataTable";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useDb, reportService } from "@/services/store";
import { FileText, Download, Plus } from "lucide-react";
import { toast } from "sonner";
import type { ReportRun } from "@/lib/types";

export const ReportsPage: React.FC = () => {
  const db = useDb();
  const [modalOpen, setModalOpen] = useState(false);

  const [formData, setFormData] = useState({
    name: "Custom Executive Summary",
    category: "Strategy",
    period: "August 2026",
    format: "PDF" as const,
  });

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    reportService.generate({
      name: formData.name,
      category: formData.category,
      period: formData.period,
      format: formData.format,
    });
    toast.success("Executive report generated and queued for download.");
    setModalOpen(false);
  };

  const handleDownload = (name: string, format: string) => {
    toast.success(`Downloading ${name} (${format})...`);
  };

  const columns: Column<ReportRun>[] = [
    { key: "id", header: "Report ID", sortable: true, className: "font-mono font-bold text-xs text-primary" },
    { key: "name", header: "Report Title", sortable: true, accessor: (r) => <span className="font-semibold text-xs text-foreground">{r.name}</span> },
    { key: "category", header: "Category", sortable: true },
    { key: "period", header: "Reporting Period", sortable: true },
    { key: "format", header: "Format", sortable: true, accessor: (r) => <span className="font-mono text-xs font-bold">{r.format}</span> },
    { key: "size", header: "File Size", sortable: true, className: "font-mono text-xs" },
    { key: "by", header: "Generated By", sortable: true },
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports & Executive Analytics"
        subtitle="Automated PDF/Excel export reports, performance scorecards, and board packs."
        breadcrumbs={[{ label: "Reports" }]}
        actions={
          <Button size="sm" onClick={() => setModalOpen(true)} className="h-9 gap-1.5 text-xs">
            <Plus className="w-4 h-4" /> Generate Report
          </Button>
        }
      />

      <DataTable
        data={db.reportHistory}
        columns={columns}
        searchPlaceholder="Search generated reports..."
        actions={(r) => (
          <Button
            variant="outline"
            size="sm"
            className="h-7 text-xs gap-1"
            onClick={() => handleDownload(r.name, r.format)}
          >
            <Download className="w-3.5 h-3.5" /> Download
          </Button>
        )}
      />

      <Dialog open={modalOpen} onOpenChange={setModalOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Generate Custom Governance Report</DialogTitle>
          </DialogHeader>
          <form onSubmit={handleGenerate} className="space-y-4 text-xs">
            <div className="space-y-1.5">
              <Label>Report Title</Label>
              <Input value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} required />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label>Category</Label>
                <Select value={formData.category} onValueChange={(val) => setFormData({ ...formData, category: val })}>
                  <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Strategy">Strategy</SelectItem>
                    <SelectItem value="KPI">KPI Scorecard</SelectItem>
                    <SelectItem value="Projects">Project Portfolio</SelectItem>
                    <SelectItem value="Risk">Risk & Audit</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1.5">
                <Label>Output Format</Label>
                <Select value={formData.format} onValueChange={(val: any) => setFormData({ ...formData, format: val })}>
                  <SelectTrigger className="h-9"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="PDF">PDF Pack</SelectItem>
                    <SelectItem value="Excel">Excel Sheet</SelectItem>
                    <SelectItem value="CSV">CSV Raw</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setModalOpen(false)}>Cancel</Button>
              <Button type="submit">Generate & Download</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
};
